### ISSUE TITLE
check_service and something else

### ISSUE THREAD

**Issue by mamatty** [MrAngius/SmartGymDev#19]
Check the method 'def check_service()' in Service.py, considering the recent creation of microservices like CustomerAccountManagerMobile.py and CustomerAccountManagerWeb.py. 
Here I report what I changed in order to obtain a proper work:

- delete this row(27) in customer_account_manager.py : 
    x["endpoint"]["broker-url"] = self.broker_ip + ":" + self.broker_port

-change 'spliit' with 'split' still in customer_account_manager.py (row 29).

- add 'web-app' in ALLOWED_CATEGORIES in Service.py.

- change, in customer_manager_mobile.conf and customer_manager_web.conf the field 'localID' with 
'local-id'.

- check in Sevice.py the following implementation starting from row 64:

            _assert isinstance(service_dict['endpoint']['params'],
                              dict), 'The "params" field for the "endpoint" should be a dictionary'
            #check the parameters definitions
            for x in service_dict['endpoint']['params'].keys():
                Service.check_service_parameter(x, service_dict['endpoint']['params'][x])_
 
and the relative method _check_service_parameter()_, considering the fact that now the field 'params' in conf_file can be also 'null' (without specifing 'type', 'optional' and 'description'). An empty dict should be allowed.

That's all. Changing this things, service and resource registrations works properly.

**Comment by gavalle94** [comment]
Sto avendo problemi ad identificare le prime due modifiche di cui sopra.
Nel dettaglio:
- non trovo il file customer_account_manager.py
- anche cercando in file simili (microservice, le 3 varianti di customer
account manager, il catalog...), non trovo le righe di codice citate
- cercando nei commit di website-migration, non trovo comunque le modifiche
citate

Ho bisogno di qualche dritta in più su come e dove reperire il codice (path
completo o URL al sorgente).
Altrimenti, vi propongo di inviarmi direttamente il codice del file in
questione.

Riguardo il resto, trovate le modifiche qui:
https://github.com/MrAngius/SmartGymDev/commit/5af225cfccbc9708b18fe3d0a5c8e06400cf13db

Il giorno mar 4 set 2018 alle ore 13:45 mamatty <notifications@github.com>
ha scritto:
