### ISSUE TITLE
Make the config_file compatible with the new modification for both resources and service

### ISSUE THREAD

**Issue by MrAngius** [MrAngius/SmartGymDev#7]
Did we do that? Need to be properly checked.

**Comment by gavalle94** [comment]
Resources and Services are instantiated according to the config_file syntax highlited by dummy JSON files under /tests/dummies. 
By the way, the question is not clear for me: which "new modifications" are you considering?

**Comment by MrAngius** [comment]
The question was generated from the project task. Was still in progress and I was wondering if it was solved or not. But I think we did it. I need a conformation.
